### ISSUE TITLE
NeoFrame crashes when used in net8 app

### ISSUE THREAD

**Issue by softlion** [felipebaltazar/Maui.NeoControls#8]

**Comment by softlion** [comment]
Retried with the prerelease

**Comment by softlion** [comment]
```
System.TypeLoadException: Could not resolve type with token 0100006e from typeref (expected class 'CropRect' in assembly '')
   at Maui.NeoControls.NeoView.DrawOuterShadow(RenderContext context) in D:\a\Maui.NeoControls\Maui.NeoControls\Maui.NeoControls\NeoView.xaml.cs:line 223
   at Maui.NeoControls.NeoView.OnCanvasViewPaintSurface(Object sender, SKPaintSurfaceEventArgs args) in D:\a\Maui.NeoControls\Maui.NeoControls\Maui.NeoControls\NeoView.xaml.cs:line 162
   at SkiaSharp.Views.Maui.Controls.SKCanvasView.OnPaintSurface(SKPaintSurfaceEventArgs e) in D:\a\_work\1\s\source\SkiaSharp.Views.Maui\SkiaSharp.Views.Maui.Controls\SKCanvasView.cs:line 50
   at SkiaSharp.Views.Maui.Controls.SKCanvasView.SkiaSharp.Views.Maui.ISKCanvasView.OnPaintSurface(SKPaintSurfaceEventArgs e) in D:\a\_work\1\s\source\SkiaSharp.Views.Maui\SkiaSharp.Views.Maui.Controls\SKCanvasView.cs:line 62
   at SkiaSharp.Views.Maui.Handlers.SKCanvasViewHandler.OnPaintSurface(Object sender, SKPaintSurfaceEventArgs e) in D:\a\_work\1\s\source\SkiaSharp.Views.Maui\SkiaSharp.Views.Maui.Core\Handlers\SKCanvasView\SKCanvasViewHandler.Android.cs:line 65
   at SkiaSharp.Views.Android.SKCanvasView.OnPaintSurface(SKPaintSurfaceEventArgs e)
   at SkiaSharp.Views.Android.SKCanvasView.OnDraw(Canvas canvas)
   at Android.Views.View.n_OnDraw_Landroid_graphics_Canvas_(IntPtr jnienv, IntPtr native__this, IntPtr native_canvas) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.View.cs:line 18998
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
```

Happen with nugets version (both stable and preelease). With a project reference, it is working.

**Comment by felipebaltazar** [comment]
@softlion thanks for the contribution.

Can you create a sample that can simulate the problem? I just tested it and it seems to work very well
[NeoControlsTest.zip](https://github.com/user-attachments/files/16831826/NeoControlsTest.zip)

**Comment by felipebaltazar** [comment]
Looking for the call stack it seems to be associated with the SkiaSharp version...
